# Generated by Django 5.1.3 on 2024-11-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dni', models.CharField(max_length=12, unique=True)),
                ('celphone', models.CharField(max_length=15)),
                ('observation', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='client')),
                ('active_membership', models.BooleanField(default=False)),
                ('active_until', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
