# Generated by Django 5.1.3 on 2024-11-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(default='Cdla Comegua Vilaa 50', max_length=200),
            preserve_default=False,
        ),
    ]
